config/routes.rb
Poker::Application.routes.draw do
 root to: 'home#index'
  resources :questions  
end

app/models/agent.rb
class Agent
	require 'csv'

	def inventory_constructor
		file = IO.readlines('CardShark-Inventory-Export-20140627.txt')
		card_info_array = []
		file.each do |element| 
		 	element = element.gsub!(/\t/, "&&")
			 	if element.include?("&&&&")
			 		element.gsub!(/&&&&/, "&&False&&")
			 	else
			 		element.gsub!(/Foil/, "true")
			 	end
		 	card_info_array << element.gsub!(/&&/, "\t")[0..-3] 
		end

		card_info_array.each do |info_pack|
			info = info_pack.split("\t")
			Card.create(set: info[0],
						name: info[1],
						rarity: info[2],
						foil: info[3],
						condition: info[4],
						price: info[5],
						quantity: info[6])
		end
	end

		def strikezone_constructor
		card_info_array = []
		file = IO.readlines("Strikezone.txt")
		file.each {|l| card_info_array << l.squeeze!.split("\t")}
		card_info_array.each do |info|
			Buycard.create(set: info[0].strip, 
										name: info[1].strip,
										foil: info[2].include?("Foil"), 
										price: info[-1].to_f, 
										quantity: info[3].to_i)
		end
	end

	def mtgfanatic_constructor
		build_card = []
		card_info_array = []
		array = CSV.read('MtgFanatic-Buylist.csv')
		array.each {|i| i.shift}
		array.each {|i| i.pop}
		array.each do |item|
			build_card << item[0].split(" - ").first
			build_card << item[0].split(" - ").last.match(/^[^\(]*/).to_s.strip
			build_card << item.to_s.include?("foil" || "Foil")
			build_card << item.to_s.include?("Played" || "played")
			build_card << item[-2].gsub(/\$/, "").to_f
			build_card << item.last.to_i
			card_info_array << build_card
			build_card = []
		end
		card_info_array.each do |info|
			Buycard.create(set: info[0],
						name: info[1],
						foil: info[2],
						played: info[3],
						price: info[4],
						quantity: info[5])
		end
	end

	def get_all_matches
		Card.all.each do |card|
			sniff = Buycard.where("name = ? AND set = ? AND foil = ?", card.name, card.set, card.foil)
			if sniff.first
				if price_filter(card, sniff.first)
					Hit.create(card_id: card.id, buycard_id: sniff.first.id, price: sniff.first.price, quantity: compute_quantity(card, sniff.first))
				end
			end
		end
	end

	def write_matches(rar)
		File.open("#{rar}_sales.txt", 'w') do |file| 
			Hit.all(:order => "price").reverse.each do |hit|
				if hit.card.rarity == rar
					string = hit.card.name + " -- " + hit.card.condition + " -- " + hit.card.set + " -- " + (hit.card.foil ? "Foil" : "    ") + " --- " + hit.quantity.to_s + " --- " + hit.price.to_s
					file.write(string + "\n")
				end
			end
		end
	end

	def total_value(rar)
		total = 0
		Hit.all.each {|hit| hit.card.rarity == rar ? total += hit.price*hit.quantity : ''}
		total
	end

	def compute_quantity(inv_card, list_card)
		if list_card.quantity > inv_card.quantity
			inv_card.quantity
		else
			list_card.quantity
		end
	end

	def name_filter(inv_card)
		Buycard.find_by_name(inv_card.name)
	end

	def set_filter(inv_card)
		Buycard.find_by_set(inv_card.set)
	end

	def foil_filter(inv_card)
		Buycard.find_by_foil(inv_card.foil)
	end

	def price_filter(inv_card, buylist_card)
		if (buylist_card.price / inv_card.price) > 0.01
			true
		end
	end
end

app/models/buycard.rb
class Buycard < ActiveRecord::Base
	has_many :hits
end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :hits
end	

app/models/hit.rb
class Hit < ActiveRecord::Base
	belongs_to :card
	belongs_to :buycard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@question = Question.new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    @question = Question.create(question_params)
    redirect_to :back
  end

  def show
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.all.last
    @question.find_the_answer
    redirect_to :back
  end

private
  def question_params
    params.require(:question).permit(:text, :choice1, :choice2, :choice3, :choice4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>PicAIune Quiz Machine</h1>

<h3>PicAIune can currently answer only multiple choice questions, please enter your question in the text box below along with 2 or more possible answer choices and press "Cross Your Fingers"! <br> Then push "Show me the Answer" to receive PicAIune's response.</h3>

<div class="question_form">
		<%= form_for @question do |f| %>
			<%= f.label :text, "Your Question Here" %>
			<%= f.text_area :text, :cols => 35, :rows => 5 %><br>
			<%= f.label :choice1 %>
			<%= f.text_field :choice1 %><br>
			<%= f.label :choice2 %>	
			<%= f.text_field :choice2 %><br>
			<%= f.label :choice3 %>	
			<%= f.text_field :choice3 %><br>
			<%= f.label :choice4 %>
			<%= f.text_field :choice4 %><br>
			<%= f.submit "Cross Your Fingers" %>
		<% end %> 
</div>

<% unless Question.all.last.text.blank? %>
	<%= button_to "Show me the Answer", question_path(Question.all.last.id), method: :patch %>
<% end %>

<% if Question.all.last %>
	<% unless Question.all.last.text.blank? %>
		<strong><%= "I think this is a \"#{Question.all.last.question_type}\" question" %><br>
		<%= "The operative word or phrase appears to be \"#{Question.all.last.operative_word.gsub(/%20/, ' ')}\"" %></strong>
	<%end%>
<%end%>

<div class="answer">
<% unless Question.all.last.answer.blank? %>
	<%= Question.all.last.answer %>
	<%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>PicAIune | Quiz Computer</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<container>
<%= render "navbar" %>

<%= yield %>

</body>
</html>